#!/usr/bin/env python3
"""
Convert client-review markdown files to DOCX for internal review.

Reads MD files generated by tools/html-to-client-review-md.py and produces
.docx files with proper heading hierarchy, bullet lists, tables, and hyperlinks.

Usage:
    python3 tools/md-to-docx.py boiler chiller fermenter mill pulverizer
    python3 tools/md-to-docx.py --all
"""

import re
import sys
import argparse
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.enum.text import WD_ALIGN_PARAGRAPH

BASE_DIR = Path(__file__).resolve().parent.parent
MD_DIR = BASE_DIR / "docs" / "client-review"
OUT_DIR = BASE_DIR / "docs" / "new-pages-for-review"


DISPLAY_NAMES = {
    "boiler-index": "Boilers",
    "chiller-index": "Chillers",
    "fermenter-index": "Fermenters",
    "mill-index": "Mills",
    "pulverizer-index": "Pulverizers",
    "reactor-tubular": "Tubular Reactors",
}


# ── inline-markdown → runs ─────────────────────────────────────────────────

INLINE_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
INLINE_BOLD = re.compile(r"\*\*([^*]+)\*\*")
INLINE_ITALIC = re.compile(r"(?<!\*)\*([^*]+)\*(?!\*)")
INLINE_CODE = re.compile(r"`([^`]+)`")


def _add_hyperlink(paragraph, url, text):
    """Add a clickable hyperlink to a paragraph (blue + underline)."""
    part = paragraph.part
    r_id = part.relate_to(
        url,
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
        is_external=True,
    )
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)
    new_run = OxmlElement("w:r")
    rpr = OxmlElement("w:rPr")
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "1155CC")
    rpr.append(color)
    underline = OxmlElement("w:u")
    underline.set(qn("w:val"), "single")
    rpr.append(underline)
    new_run.append(rpr)
    text_el = OxmlElement("w:t")
    text_el.text = text
    text_el.set(qn("xml:space"), "preserve")
    new_run.append(text_el)
    hyperlink.append(new_run)
    paragraph._p.append(hyperlink)
    return hyperlink


def _add_inline(paragraph, text):
    """Add text with bold/italic/code/link parsing to a paragraph."""
    # Find all inline matches with their positions
    spans = []
    for m in INLINE_LINK.finditer(text):
        spans.append((m.start(), m.end(), "link", m.group(1), m.group(2)))
    for m in INLINE_BOLD.finditer(text):
        if not any(s[0] <= m.start() < s[1] for s in spans):
            spans.append((m.start(), m.end(), "bold", m.group(1), None))
    for m in INLINE_ITALIC.finditer(text):
        if not any(s[0] <= m.start() < s[1] for s in spans):
            spans.append((m.start(), m.end(), "italic", m.group(1), None))
    for m in INLINE_CODE.finditer(text):
        if not any(s[0] <= m.start() < s[1] for s in spans):
            spans.append((m.start(), m.end(), "code", m.group(1), None))
    spans.sort(key=lambda x: x[0])

    pos = 0
    for start, end, kind, content, extra in spans:
        if start > pos:
            paragraph.add_run(text[pos:start])
        if kind == "link":
            _add_hyperlink(paragraph, extra, content)
        elif kind == "bold":
            r = paragraph.add_run(content)
            r.bold = True
        elif kind == "italic":
            r = paragraph.add_run(content)
            r.italic = True
        elif kind == "code":
            r = paragraph.add_run(content)
            r.font.name = "Consolas"
        pos = end
    if pos < len(text):
        paragraph.add_run(text[pos:])


# ── DOCX builder ───────────────────────────────────────────────────────────

def _set_doc_defaults(doc: Document):
    """Set base font and margins."""
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)


def _parse_table_block(lines, start_idx):
    """Parse a markdown table starting at lines[start_idx]. Return (rows, end_idx)."""
    rows = []
    i = start_idx
    while i < len(lines) and lines[i].lstrip().startswith("|"):
        row = lines[i].strip().strip("|").split("|")
        rows.append([c.strip() for c in row])
        i += 1
    # rows[1] is the separator line "----"
    if len(rows) >= 2 and all(set(c.replace("-", "").replace(":", "").strip()) <= {""} for c in rows[1]):
        header = rows[0]
        body = rows[2:]
    else:
        header = rows[0]
        body = rows[1:]
    return header, body, i


def md_to_docx(md_text: str, display_name: str, out_path: Path):
    """Convert markdown text to a .docx file at out_path."""
    doc = Document()
    _set_doc_defaults(doc)

    lines = md_text.splitlines()
    i = 0
    in_list = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip blank lines
        if not stripped:
            in_list = False
            i += 1
            continue

        # Headings
        if stripped.startswith("# "):
            doc.add_heading(stripped[2:].strip(), level=1)
            i += 1
            continue
        if stripped.startswith("## "):
            doc.add_heading(stripped[3:].strip(), level=2)
            i += 1
            continue
        if stripped.startswith("### "):
            doc.add_heading(stripped[4:].strip(), level=3)
            i += 1
            continue
        if stripped.startswith("#### "):
            doc.add_heading(stripped[5:].strip(), level=4)
            i += 1
            continue
        if stripped.startswith("##### "):
            doc.add_heading(stripped[6:].strip(), level=5)
            i += 1
            continue

        # Horizontal rule
        if stripped == "---":
            p = doc.add_paragraph()
            r = p.add_run("─" * 60)
            r.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
            i += 1
            continue

        # Tables
        if stripped.startswith("|") and "|" in stripped[1:]:
            header, body, end_idx = _parse_table_block(lines, i)
            ncols = max(len(header), max((len(r) for r in body), default=0))
            table = doc.add_table(rows=1 + len(body), cols=ncols)
            table.style = "Light Grid Accent 1"
            for c, h in enumerate(header[:ncols]):
                cell = table.rows[0].cells[c]
                cell.text = ""
                p = cell.paragraphs[0]
                r = p.add_run(h)
                r.bold = True
            for r_idx, row in enumerate(body, start=1):
                for c_idx, val in enumerate(row[:ncols]):
                    cell = table.rows[r_idx].cells[c_idx]
                    cell.text = ""
                    _add_inline(cell.paragraphs[0], val)
            i = end_idx
            continue

        # Bullet list
        if stripped.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            _add_inline(p, stripped[2:].strip())
            in_list = True
            i += 1
            continue

        # Numbered list
        m = re.match(r"^(\d+)\.\s+(.+)$", stripped)
        if m:
            p = doc.add_paragraph(style="List Number")
            _add_inline(p, m.group(2))
            in_list = True
            i += 1
            continue

        # Body paragraph - may span multiple wrapped lines until a blank
        para_lines = [stripped]
        j = i + 1
        while j < len(lines) and lines[j].strip() and not _looks_like_block_start(lines[j].strip()):
            para_lines.append(lines[j].strip())
            j += 1
        para_text = " ".join(para_lines)
        p = doc.add_paragraph()
        _add_inline(p, para_text)
        i = j

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(out_path)


def _looks_like_block_start(line: str) -> bool:
    """Return True if this line is the start of a new block element."""
    if line.startswith(("#", "- ", "|", "---")):
        return True
    if re.match(r"^\d+\.\s+", line):
        return True
    return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("slugs", nargs="*", help="Slugs without -index suffix (e.g. 'boiler')")
    parser.add_argument("--all", action="store_true", help="Convert all 5 new pages")
    args = parser.parse_args()

    if args.all or not args.slugs:
        slugs = ["boiler", "chiller", "fermenter", "mill", "pulverizer"]
    else:
        slugs = args.slugs

    # Resolve slug to MD path — supports both "<slug>-index.md" and "<slug>.md" patterns
    def md_path_for(slug: str):
        for candidate in (MD_DIR / f"{slug}-index.md", MD_DIR / f"{slug}.md"):
            if candidate.exists():
                return candidate
        return None

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for slug in slugs:
        md_path = md_path_for(slug)
        if md_path is None:
            print(f"  SKIP: no MD found for slug '{slug}'")
            continue
        key = md_path.stem
        display = DISPLAY_NAMES.get(key, slug.title() + "s")
        out_path = OUT_DIR / f"{display}.docx"
        print(f"  Converting: {md_path.name} -> {out_path.name}")
        md_to_docx(md_path.read_text(encoding="utf-8"), display, out_path)
    print(f"\n  Done. Output: {OUT_DIR}")


if __name__ == "__main__":
    main()
